services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rpassword
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d

  node-service:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: database
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_ROOT_PASSWORD: rpassword
    deploy:
        replicas: 3
    depends_on:
      - db


  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-service

      

volumes:
  db-data:

# docker-compose ps
# docker-compose logs nginx

# docker-compose down
# docker-compose up --build -d
